version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - all
        path: pkg/x/*
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - govet
          - revive
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
