# change the IP address 192.168.1.2 to your local IP address or hostname in conf/dex.yaml, conf/pigo.yaml
services:
  db-postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: main
      POSTGRESQL_WAL_LEVEL: logical
    ports:
    - 5432:5432
    volumes:
    - db-postgresql:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  init-db-postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      PGHOST: db-postgresql
      PGUSER: postgres
      PGPASSWORD: postgrespw
      PGDATABASE: main
    depends_on:
      db-postgresql:
        condition: service_healthy
    entrypoint:
    - /bin/bash
    - -c
    - |
      echo "Waiting for PostgreSQL to be ready..."
      until psql -U postgres -c '\q'; do
        echo "PostgreSQL is unavailable - sleeping"
        sleep 2
      done
      echo "PostgreSQL is up - executing SQL"
      psql -c "
        DO \$\$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'dex') THEN CREATE ROLE dex WITH LOGIN PASSWORD 'dexpw'; END IF;
          IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pigo') THEN CREATE ROLE pigo WITH LOGIN PASSWORD 'pigopw'; END IF;
          IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authn') THEN CREATE ROLE authn NOLOGIN; END IF;
          IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN CREATE ROLE anon NOLOGIN; END IF;
          GRANT anon TO authn;
          GRANT authn to pigo;
        END
        \$\$;
      "

      psql -c "CREATE DATABASE dex;" || true
      psql -c "ALTER DATABASE dex OWNER TO dex;"      
    restart: on-failure
  
  iam-dex: # Identity and Access Management (AuthN/AuthZ)
    image: docker.io/edgeflare/dex
    command: 'dex serve /config.yaml'
    environment:
      DEX_CUSTOM_CLAIMS_STATIC: '{"policy": {"pgrole": "authn"}, "exampleclaim": "value"}'
    ports:
    - 5556:5556
    volumes:
    - $PWD/conf/dex.yaml:/config.yaml:rw,Z
    depends_on:
      db-postgresql:
        condition: service_healthy
    restart: on-failure

  rest-pigo: # PostgreSQL over REST API
    image: ghcr.io/edgeflare/pigo
    command: [rest, --config, /rest/config.yaml]
    ports:
    - 8001:8001
    volumes:
    - $PWD/conf/pigo.yaml:/rest/config.yaml:rw,Z
    depends_on:
      db-postgresql:
        condition: service_healthy
    restart: on-failure

volumes:
  db-postgresql:
